[log]
  level = "ERROR"
  filePath = "log-file.log"

[accessLog]
  filePath =  "log-access.log"
  bufferingSize =  100

[providers]
  [providers.file]
    filename = "traefik-dynamic.toml"

[api]
  # insecure = true
  # dashboard = false
  debug = false

[entryPoints]
  [entryPoints.web]
    address = ":8300"
  [entryPoints.web-secure]
    address = ":9443"
  # [entryPoints.dashboard]
  #  address = ":8080"

[certificatesResolvers.sample.acme]
  email = "mymail@example.com"
  storage = "acme.json"

[certificatesResolvers.sample.acme.httpChallenge]
  # used during the challenge
  entryPoint = "web-secure"
