[http]
  [http.middlewares]
    [http.middlewares.server2-stripprefix.stripPrefix]
      prefixes = ["/server2"]
    [http.middlewares.server3-stripprefix.stripPrefix]
      prefixes = ["/server3"]
    [http.middlewares.server4-stripprefix.stripPrefix]
      prefixes = ["/server4"]
    [http.middlewares.server5-stripprefix.stripPrefix]
      prefixes = ["/server5"]

  [http.routers]
    [http.routers.my-router2]
      rule = "Path(`/server2`)"
      service = "my-service2"
      entryPoints = ["web"]
      middlewares = ["server2-stripprefix"]

    [http.routers.my-router3]
      rule = "Path(`/server3`)"
      service = "my-service3"
      entryPoints = ["web"]
      middlewares = ["server3-stripprefix"]

    [http.routers.my-router4]
      rule = "Path(`/server4`)"
      service = "my-service4"
      entryPoints = ["web"]
      middlewares = ["server4-stripprefix"]

    [http.routers.my-router5]
      rule = "Path(`/server5`)"
      service = "my-service5"
      entryPoints = ["web"]
      middlewares = ["server5-stripprefix"]

    [http.routers.my-router12]
      rule = "Path(`/server2`)"
      service = "my-service2"
      entryPoints = ["web-secure"]
      middlewares = ["server2-stripprefix"]
      tls = true

    [http.routers.my-router13]
      rule = "Path(`/server3`)"
      service = "my-service3"
      entryPoints = ["web-secure"]
      middlewares = ["server3-stripprefix"]
      tls = true

    [http.routers.my-router14]
      rule = "Path(`/server4`)"
      service = "my-service4"
      entryPoints = ["web-secure"]
      middlewares = ["server4-stripprefix"]
      tls = true

    [http.routers.my-router15]
      rule = "Path(`/server5`)"
      service = "my-service5"
      entryPoints = ["web-secure"]
      middlewares = ["server5-stripprefix"]
      tls = true

  [http.services]
    [http.services.my-service2.loadBalancer]
      passHostHeader = false
      [[http.services.my-service2.loadBalancer.servers]]
        url = "http://127.0.0.1:10082/"

    [http.services.my-service3.loadBalancer]
      passHostHeader = false
      [[http.services.my-service3.loadBalancer.servers]]
        url = "http://127.0.0.1:10083/"

    [http.services.my-service4.loadBalancer]
      passHostHeader = false
      [[http.services.my-service4.loadBalancer.servers]]
        url = "http://127.0.0.1:10084/"

    [http.services.my-service5.loadBalancer]
      passHostHeader = false
      [[http.services.my-service5.loadBalancer.servers]]
        url = "http://127.0.0.1:10085/"
