[package]
name = "monolake"
version = "0.2.0"
edition = "2021"
keywords = ["monoio", "http", "async"]
description = "High Performance Proxy base on Monoio"

[dependencies]
monoio = { version = "0.1.4", features = ["sync", "async-cancel"] }
monolake-core = { path = "../monolake-core" }
monolake-services = { path = "../monolake-services" }
service-async = "0.1"

# tls: needed for native-tls init
monoio-native-tls = { version = "0.1.0" }

# error
thiserror = "1"
anyhow = "1"

# log
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# parse
clap = { version = "4", features = ['derive'] }
serde = "1"
serde_json = "1"
serde_derive = "1"
http = "0.2"

# futures
futures-util = { version = "0.3", features = ["sink"] }
futures-channel = { version = "0.3", features = ["sink"] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.5"
