[package]
name = "monolake"
version = "0.2.0"
edition = "2021"
keywords = ["monoio", "http", "async"]
description = "Proxy solution base on monoio"

[dependencies]
monolake-core = { path = "../monolake-core" }
monolake-services = { path = "../monolake-services" }

monoio = { version = "0.1.3", features = ["sync"] }
monoio-http = "0.1.0"
monoio-http-client = { version = "0.1.0", features = ["logging", "tls"] }

monoio-rustls = { version = "0.1.2" }

monoio-native-tls = { version = "0.1.0" }
native-tls = "0"
openssl-sys = "0"

bytes = "1"
http = "0.2"
httparse = "1"
thiserror = "1"
anyhow = "1"
# logger
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ['derive'] }

serde = "1"
serde_json = "1"
serde_derive = "1"
tower-layer = "0"

futures-util = { version = "0.3", features = ["sink"] }
futures-channel = { version = "0.3", features = ["sink"] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.5"
