[package]
name = "monoio-gateway-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monoio-gateway = {path = '../monoio-gateway'}
monoio = {path = '../../monoio/monoio'}


[[example]]
name = "tcp-proxy"
path = "tcp_proxy.rs"

[[example]]
name = "server"
path = "server.rs"