[runtime]
# runtime_type = "Legacy"
workers = 1
entries = 8192

# server1
[servers.server1]
name = "gateway.example.com"
listeners = [
    { socket_addr = "0.0.0.0:8080" },
    { uds_path = "examples/tmp/test.sock" },
]

[[servers.server1.routes]]
upstreams = [
    { endpoint = { uri = "http://127.0.0.1:9080" } },
    { endpoint = { uri = "http://127.0.0.1:10080" } },
]
path = '/'


[[servers.server1.routes]]
upstreams = [
    { endpoint = { uri = "http://127.0.0.1:9080" } },
    { endpoint = { uri = "http://127.0.0.1:10080" } },
]
path = '/*p'

# server2
[servers.server2]
tls = { chain = "examples/tmp/certs/cert.pem", key = "examples/tmp/certs/key.pem" }
name = "gateway.example.com"
listeners = [{ socket_addr = "0.0.0.0:8081" }]

[[servers.server2.routes]]
path = '/'
upstreams = [{ endpoint = { uri = "http://127.0.0.1:9080" } }]

[[servers.server2.routes]]
path = '/*p'
upstreams = [{ endpoint = { uri = "http://127.0.0.1:9080" } }]


# server3
[servers.server3]
tls = { chain = "examples/tmp/certs/cert.pem", key = "examples/tmp/certs/key.pem" }
name = "gateway.example.com"
listeners = [{ socket_addr = "0.0.0.0:8082" }]

[[servers.server3.routes]]
path = '/'
upstreams = [{ endpoint = { uri = "https://www.wikipedia.org" } }]
