[runtime]
# runtime_type = "legacy"
worker_threads = 2
entries = 1024

[servers.demo_basic]
name = "gateway.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8080" }
upstream_http_version = "http2"

[[servers.demo_basic.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "https://www.bytedance.com/" } }]

[[servers.demo_basic.routes]]
path = '/github'
upstreams = [{ endpoint = { type = "uri", value = "https://github.com/" } }]


[servers.demo_tls]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.key" }
name = "gateway.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8081" }
upstream_http_version = "http11"
http_timeout = { server_keepalive_timeout_sec = 60, upstream_connect_timeout_sec = 2, upstream_read_timeout_sec = 2 }

[[servers.demo_tls.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]

[[servers.demo_tls.routes]]
path = '/{*p}'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]


[servers.demo_uds]
name = "gateway.monolake.rs"
listener = { type = "unix", value = "/tmp/monolake.sock" }

[[servers.demo_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/'

[[servers.demo_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/{*p}'


[servers.demo_rustls]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.key", stack = "rustls" }
name = "gateway.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8082" }

[[servers.demo_rustls.routes]]
path = '/'
upstreams = [
    { endpoint = { type = "uri", value = "https://www.wikipedia.org" } },
]


[servers.demo_native_tls]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.key", stack = "native_tls" }
name = "gateway.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8083" }

[[servers.demo_native_tls.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "https://www.wikipedia.org" } },
]
path = '/'


[servers.demo_timeout]
name = "timeout.com"
listener = { type = "socket", value = "0.0.0.0:8084" }
http_timeout = { server_read_header_timeout_sec = 2 }

[[servers.demo_timeout.routes]]
path = '/ping'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:9080" } }]
