[runtime]
# runtime_type = "legacy"
worker_threads = 2
entries = 1024


[servers.server_basic]
name = "monolake.cloudwego.io"
listener = { type = "socket", value = "0.0.0.0:8080" }

[[servers.server_basic.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:9080" } }]

[[servers.server_basic.routes]]
path = '/*p'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:9080" } }]


[servers.server_tls]
tls = { chain = "examples/certs/cert.pem", key = "examples/certs/key.pem" }
name = "monolake.cloudwego.io"
listener = { type = "socket", value = "0.0.0.0:8081" }

[[servers.server_tls.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]

[[servers.server_tls.routes]]
path = '/*p'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]


[servers.server_uds]
name = "monolake.cloudwego.io"
listener = { type = "unix", value = "/tmp/monolake.sock" }

[[servers.server_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/'


[[servers.server_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/*p'


[servers.server3]
tls = { chain = "examples/certs/cert.pem", key = "examples/certs/key.pem", stack = "rustls" }
name = "monolake.cloudwego.io"
listener = { type = "socket", value = "0.0.0.0:8082" }

[[servers.server3.routes]]
path = '/'
upstreams = [
    { endpoint = { type = "uri", value = "https://www.wikipedia.org" } },
]


[servers.server4]
tls = { chain = "examples/certs/cert.pem", key = "examples/certs/key.pem", stack = "native_tls" }
name = "monolake.cloudwego.io"
listener = { type = "socket", value = "0.0.0.0:8083" }

[[servers.server4.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "https://www.wikipedia.org" } },
]
path = '/'
