[runtime]
# runtime_type = "legacy"
workers = 1
entries = 8192


[servers.server_basic]
name = "proxy.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8080" }

[[servers.server_basic.routes]]
path = '/'
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" }, version = "HTTP2" },
]

[[servers.server_basic.routes]]
path = '/*p'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:9080" } }]


[servers.server_tls]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.pkcs8" }
name = "proxy.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8081" }

[[servers.server_tls.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]

[[servers.server_tls.routes]]
path = '/*p'
upstreams = [{ endpoint = { type = "uri", value = "http://127.0.0.1:8080" } }]


[servers.server_uds]
name = "proxy.monolake.rs"
listener = { type = "unix", value = "/tmp/monolake.sock" }

[[servers.server_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/'


[[servers.server_uds.routes]]
upstreams = [
    { endpoint = { type = "uri", value = "http://127.0.0.1:9080" } },
    { endpoint = { type = "uri", value = "http://127.0.0.1:10080" } },
]
path = '/*p'


[servers.server3]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.pkcs8", stack = "rustls" }
name = "proxy.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8082" }

[[servers.server3.routes]]
path = '/'
upstreams = [{ endpoint = { type = "uri", value = "https://rsproxy.cn" } }]


[servers.server4]
tls = { chain = "examples/certs/server.crt", key = "examples/certs/server.pkcs8", stack = "native_tls" }
name = "proxy.monolake.rs"
listener = { type = "socket", value = "0.0.0.0:8083" }

[[servers.server4.routes]]
upstreams = [{ endpoint = { type = "uri", value = "https://rsproxy.cn" } }]
path = '/'
