[package]
name = "monolake-services"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


monoio = { features = ['splice'], version = "0.1.2" }
monolake-core = { path = "../monolake-core" }
monoio-http = { git = "https://github.com/monoio-rs/monoio-http.git", branch = "conn-pool-fix" }
monoio-http-client = { git = "https://github.com/monoio-rs/monoio-http.git", branch = "conn-pool-fix", features = [
    "logging",
    "tls",
] }


anyhow = "1"
log = "0.4"
http = "0.2"
bytes = "1"

monoio-rustls = { version = "0.1.2" }
rustls = { version = "0.21" }
rustls-pemfile = "1"
webpki-roots = "0.23"

monoio-native-tls = { version = "0.1.0" }
native-tls = "0.2"
openssl-sys = "0.9"


async-channel = "1"
tower-layer = "0"
rand = "0"
matchit = "0"
ppp = "2"
