[package]
name = "monolake-services"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
openid = [
    "dep:cookie",
    "dep:openidconnect",
    "dep:serde",
    "dep:thiserror",
    "dep:url",
]

[dependencies]
monoio = { version = "0.1.4", features = ['splice'] }
monolake-core = { path = "../monolake-core" }
monoio-http = "0.1.0"
monoio-http-client = { version = "0.1.2", features = ["logging", "rustls"] }

anyhow = "1"
tracing = "0.1"
http = "0.2"
bytes = "1"
lazy_static = "1.4.0"

monoio-rustls = { version = "0.1.2" }
rustls = { version = "0.21" }
rustls-pemfile = "1"
webpki-roots = "0.23"

monoio-native-tls = { version = "0.1.0" }
native-tls = "0.2"
openssl-sys = "0.9"

async-channel = "1"
tower-layer = "0"
rand = "0"
matchit = "0"
ppp = "2"
pin-project-lite = "0.2"
service-async = "0.1"

cookie = { version = "0.17", optional = true }
openidconnect = { version = "3.0.0", optional = true }
serde = { version = "1.0.163", optional = true }
thiserror = { version = "1.0.24", optional = true }
url = { version = "2.3.1", optional = true }
