[package]
name = "monolake-services"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


monoio = { version = "0.1.3", features = ['splice'] }
monolake-core = { path = "../monolake-core" }
monoio-http = "0.1.0"
monoio-http-client = { version = "0.1.0", features = ["logging", "tls"] }


anyhow = "1"
tracing = "0.1"
http = "0.2"
bytes = "1"

monoio-rustls = { version = "0.1.2" }
rustls = { version = "0.21" }
rustls-pemfile = "1"
webpki-roots = "0.23"

monoio-native-tls = { version = "0.1.0" }
native-tls = "0.2"
openssl-sys = "0.9"

async-channel = "1"
tower-layer = "0"
rand = "0"
matchit = "0"
ppp = "2"
pin-project-lite = "0.2"
